lang: ruby

install:
  - gem update --system
  - bundle update

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - ruby-head

notifications:
  recipients:
    - luiz.rocha@abril.com.br

branches:
  only:
  - master

