#!/usr/bin/env ruby
# File: script/console
irb = RUBY_PLATFORM =~ /(:?mswin|mingw)/ ? 'irb.bat' : 'irb'
libs = " -r #{File.expand_path(File.dirname(__FILE__)) + '/../lib/browsah.rb'}"
puts "Loading gem development environment..."
exec "#{irb} #{libs} --simple-prompt #{ARGV.join("")}"
